os: linux
dist: jammy
language: minimal

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
  - stage: test
    name: "conda linux"
    os: linux
    dist: jammy
    env: TEST_PROFILE="proteus-conda"
    install:
      - git lfs pull
      - sudo apt-get update
      - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge3.sh;
      - bash miniforge3.sh -b -p $HOME/miniforge3
      - source "$HOME/miniforge3/etc/profile.d/conda.sh"
      - source "$HOME/miniforge3/etc/profile.d/mamba.sh"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - mamba init
      - mamba update -q conda mamba
      - mamba info -a
      - mamba env create -f environment-dev.yml
      - mamba activate proteus-dev
      - pip install -v . --no-build-isolation --no-binary=":all:"
    script:
      - export MPLBACKEND="AGG"
      - mkdir test_output
      - cd test_output
      - py.test -v --forked --import-mode=importlib ../test
