name: proteus-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip =24.0
  - compilers =1.7.0
  - make =4.4.1
  - setuptools =73.0.1
  - cython =3.0.11
  - hdf5 =1.14.3=*mpich*
  - h5py =3.11.0=*mpich*
  - metis =5.1.0
  - mpich =4.2.2
  - mpich-mpicc =4.2.2
  - mpich-mpicxx =4.2.2
  - numpy =2.1.1
  - openblas =0.3.28
  - parmetis =4.0.3
  - petsc4py =3.21.5
  - petsc =3.21.5
  - scorec =2.2.8
  - superlu =5.2.2
  - superlu_dist =9.0.0
  - triangle =1.6
  - pychrono =9.0.1
  - gmsh =4.12.2
  - matplotlib =3.9.2
  - mpi4py =4.0.0
  - pytest =8.3.3
  - pytest-cov =5.0.0
  - pytest-xdist =3.6.1
  - pytest-forked
  - scipy =1.14.1
  - tetgen =1.6.0
  - ncurses =6.5
  - python =3.12.5
  - xtensor-python = 0.27.0
  - git-lfs =3.5.1
  - eigen =3.4.0
  - zoltan =3.901
  - hypre =2.31.0
  - mumps-mpi =5.7.3
  - scalapack =2.2.0
  - tbb =2021.13.0
  - zipp =3.20.1
  - parso =0.8.4
  - pycparser =2.22
  - cffi =1.17.1
  - sympy =1.13.2