name: proteus-dev-up-240912
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - compilers
  - make
  - setuptools
  - cython
  - pybind11
  - hdf5 =*=*mpich*
  - h5py =*=*mpich*
  - metis
  - mpich
  - mpich-mpicc
  - mpich-mpicxx
  - numpy
  - openblas
  - parmetis
  - petsc4py
  - petsc
  - superlu
  - superlu_dist
  - scorec >=2.2.8
  - triangle
  - pychrono >=9.0.1
  - gmsh
  - matplotlib
  - mpi4py
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy
  - tetgen
  - ncurses
  - python
  - ipyparallel
  - xtensor-python
  - git-lfs
  - eigen
  - zoltan
  - hypre
  - tbb
  - zipp
  - parso
  - pycparser
  - ipython
  - decorator
  - cffi
  - jupyterlab
  - openmp
