[build-system]
requires = ["setuptools>=61.0","cython==3.0.0","pybind11==2.11.1","numpy==1.25.1","mpi4py"]#"h5py","numpy","scipy","pybind11","swig"]#"petsc4py","mpi4py",
build-backend = "setuptools.build_meta"
